name: publish
on: [push]
jobs:
  publish-php82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the php82 Docker image
        run: |
          docker build . --tag ghcr.io/luya/nginx-fpm-php82:latest -f nginx-fpm-php82/Dockerfile
          docker run ghcr.io/luya/nginx-fpm-php82:latest
          docker push ghcr.io/luya/nginx-fpm-php82:latest